#!/bin/sh

cat <<'License'
    Lilacin installs Larbs after customizing it nicely.
    Copyright (C) 2021 Lin2Jing4

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
License

## download progs.csv from Luke's repo
curl -O https://raw.githubusercontent.com/LukeSmithxyz/LARBS/master/progs.csv
## customize progs.csv for your own needs
sed -i '
  /gtk-theme-arc-gruvbox-git/d
  /mpc/d
  /mpd/d
  /ncmpcpp/d
  /ttf-linux-libertine/d
  /unclutter/d
  /xcompmgr/d
  /xwallpaper/d
  ' progs.csv
cat <<'progs.csv' >>'progs.csv'
  ,libreoffice-fresh,"is the feature branch, with new program enhancements."
  ,noto-fonts-cjk,"covers Chinese, Japanese, and Korean font family."
  ,fcitx-chewing,"is a Zhuyin input engine for Chinese based on libchewing."
  ,fcitx-configtool,"is a GTK3 based configuration tool for Fcitx."
progs.csv

## download larbs.sh from Luke's repo
curl -O https://raw.githubusercontent.com/LukeSmithxyz/LARBS/master/larbs.sh
## customize larbs.sh for your own needs
sed -i '/refreshkeys/a pacman -Syyu --noconfirm' larbs.sh
cat <<'larbs.sh' >>'larbs.sh'
  sed -i '
    $a VBoxClient --vmsvga
    $a fcitx &
    $a (sleep 9 && xdotool key Super+a) &
  ' /home/$name/.config/x11/xprofile
larbs.sh

## install the configured Larbs with a custom programs list
sh larbs.sh -p progs.csv
